CREATE DATABASE result_mgm 

CREATE TABLE `Student` (
	`MatricNo`	CHAR(14) NOT NULL UNIQUE,
	`Name`	VARCHAR(50) NOT NULL,
	`Class`	VARCHAR(10) NOT NULL,
	`IndexNo`	INTEGER NOT NULL,
	`Gender`	CHAR(1) NOT NULL,
	PRIMARY KEY(`MatricNo`)
);

CREATE TABLE `Test` (
	`TestID`	INTEGER NOT NULL PRIMARY KEY,
	`Subject`	VARCHAR(50) NOT NULL,
	`Level`	CHAR(3) NOT NULL,
	`MaxScore`	INTEGER NOT NULL,
	`Year`	INTEGER NOT NULL,
	`Term`	INTEGER NOT NULL,
	`Percentage`	INTEGER NOT NULL
);

CREATE TABLE `Result` (
	`MatricNo`	CHAR(14) NOT NULL UNIQUE,
	`TestID`	INTEGER NOT NULL PRIMARY KEY,
	`Score`	INTEGER NOT NULL,
	FOREIGN KEY(`TestID`) REFERENCES `Test`(`TestID`),
	FOREIGN KEY(`MatricNo`) REFERENCES `Student`(`MatricNo`)
);