SELECT SALE.SaleDate, SALESPERSON.SalesPersonName, CUSTOMER.CustomerName, SALE.Amount
FROM SALE, SALESPERSON, CUSTOMER
WHERE SALESPERSON.OfficeID = 1 AND SALE.SalesPersonID = SALESPERSON.SalesPersonID AND 
CUSTOMER.CustomerID = SALE.CustomerID