# -*- coding: utf-8 -*-
"""CP7 Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gjDj7annG67zUjaCDjFSVjpjGNGhcWd6

#Check Point 7 (Dictionary)
"""

# Q1. Increasing the Values in a Simple Dictionary  [4 marks]

def increase_by_one(d):
    for key in d.keys():
        d[key] += 1
    return d

##print(increase_by_one({'first':27, 'second':16, 'third':8}))#=={'first': 28, 'second': 17, 'third': 9}))








# Q2. Combine 2 dictionaries (5 marks)
#method 1
def combine(d1, d2):
    new_dict = {}
    for key in d1:
        if key not in new_dict:
            new_dict[key] = d1[key]
    for key2 in d2:
        for keys in new_dict:
            if keys == key2:
                new_dict[keys] += d2[key2]
        if key2 not in new_dict:
            new_dict[key2] = d2[key2]

    return new_dict


#method 2
def combine2(d1, d2):
    new_d = {}
    for k1, v1 in d1.items():
        if k in d2:
            total = v + d2[k1]
            new_d[k] = total
        else:
            total = v
            new_d[k] = total

    for k2, v2 in d2.items():
        if k2 not in d2.items():
            pass
            
        
        
# Do not modify the following:
John = {'burger':2, 'ice milo':1, 'fries':1}
Mary = {'burger':1, 'coke':1, 'apple pie':2, 'fries':1}

##print(combine(John, Mary)=={'burger':3, 'coke':1, 'apple pie':2, 'ice milo':1, 'fries':2})








# Q3. Upsize Player's inventory by Looting  [6 marks]

def add_inv(inv, items):
    pass
    if items == []:
        return inv
    else:
        new_dict = {}

        for key in inv:
            new_dict[key] = inv[key]

        for ele in items:
            if ele not in new_dict:
                new_dict[ele] = 1
        
        for ele in items:
            for key in inv:
                if ele == key:
                    new_dict[key] += 1

        return new_dict


#correction
def add_inv2(inv, items):
    for ele in items:
        if ele in inv:
            inv[ele] += 1
        else:
            inv[ele] = 1
    items.clear()
    return inv







    
# Do not modify the following:
my_bag = {'coin': 2, 'health_pot': 3, 'mana_pot': 5, 'scroll': 2, 'dagger': 1, 'ore': 3, 'mace': 1, 'gloves': 1}
barlog_loot = ['leather', 'sword', 'scroll', 'scroll', 'coin', 'coin', 'helmet']

##print(add_inv(my_bag, barlog_loot))=={'coin': 4, 'health_pot': 3, 'mana_pot': 5, 'scroll': 4, 'dagger': 1, 'ore': 3, 'mace': 1, 'gloves': 1, 'leather':1, 'sword':1, 'helmet':1})







# Q4. Exchange inventory for coins (5 marks)

def change_coin(inv):
    new_dict = {}
    for keys in exchange_rate:
        for key in inv:
            if keys == key:
                inv['coin'] += exchange_rate[keys] * inv[key]
    new_dict['coin'] = inv['coin']
    return new_dict
        


# Do not modify the following:
my_bag = {'coin': 50, 'leather': 25, 'wood': 16, 'scroll': 3, 'ore': 14}
exchange_rate={'leather':50,'ore':10,'wood':5, 'scroll':20}

##print(change_coin(my_bag)['coin'])==1580)









#question 5
def total(inv):
    total = 0
    for values in inv.values():
        total += values
    return total

my_bag = {'coin': 50, 'leather': 25, 'wood': 16, 'scroll': 3, 'ore': 14}
##print(total(my_bag))










#question 6(bonus)
def add_inv(inv, items):
    a = 50 - total(inv)
    lst = []
    lst += items[:a]
    for ele in lst:
        if ele in inv:
            inv[ele] += 1
        else:
            inv[ele] = 1
    del items[:a]
    return inv
        
    
almost_full_bag = {'coin': 10, 'health_pot': 13, 'mana_pot': 15, 'scroll': 2, 'dagger': 1, 'ore': 3, 'mace': 1,'gloves': 1}
kratos_loot = [ 'leather', 'sword', 'scroll', 'scroll', 'coin', 'coin', 'helmet' ]

print(add_inv(almost_full_bag, kratos_loot))
print(kratos_loot)
